# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Brennan McDavid
tagline:          'A Jekyll theme'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Brennan McDavid'
  url:            https://bkmcdavid.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
